### ISSUE TITLE
Track: Website layout creation [ One File at once please]

### ISSUE THREAD

**Issue by ShivamTyagi12345** [dokc/dokc.github.io#34]
**1 .HOMEPAGE ( concerned Folder to work with :`src\components` )**
  - [ ] What is the DoKC / our aim? [dokc/dokc.github.io/pull/50]
  - Basic explanation of what dok is
     - [ ] #64
     - [ ] Stateful vs stateless 
  - [ ] why data on Kubernetes?

**2  .DOCS ( concerned Folder to work with :`docs\Documentation` )**
  -  Getting Started 
     - [ ] About the project
     - [ ] Aim/Goal trying to achieve
     - [ ] A brief explanation of project architecture and different components
  - Setting up the project locally
     - [ ] Installation Requirements
     - [ ] #65
     - [ ] #66
     - [ ] #67
     - [ ] #68

- [ ]  Guide to contribute to the documentation

**3  .TUTORIALS( concerned Folder to work with :`docs\Tutorials` )**
  - [ ] Resources for newcomers with Roadmap 
  - [ ] Community talks/live streams
  

  **`important>`** Color scheme to be followed throughout:
  
<img width="384" alt="image" src="https://user-images.githubusercontent.com/60812924/159144905-1e6c4952-d3bb-4836-8eb1-8f1ab80f18b2.png">

**Comment by Aayush987** [comment]
Hi,I would like to work on " what is the DoKC/ our aim . Please assign me.

**Comment by subhamgcon** [comment]
I want to work on the "Our Sponsor" part of the website

**Comment by AbhijithGanesh** [comment]
@ShivamTyagi12345 I'd like this to be broken into sub issues!

**Comment by AbhijithGanesh** [comment]
Unfortunately  @subhamgcon , that part alone is not up for grabs. We have to remove it because we have a change in the plan!

**Comment by subhamgcon** [comment]
> Unfortunately @subhamgcon , that part alone is not up for grabs. We have to remove it because we have a change in the plan!
Then Can I work on the "Stateful vs stateless" part of the project?

**Comment by subhamgcon** [comment]
@AbhijithGanesh Then Can I work on the "Stateful vs stateless" part of the project?
