### ISSUE TITLE
[Feature]: Missing issue template

### ISSUE THREAD

**Issue by cnu1812** [dokc/dokc.github.io#36]

**Comment by subhamgcon** [comment]
Hey @cnu1812, Can I work on it?

**Comment by cnu1812** [comment]
Go ahead @subhamgcon will be assign to you!

**Comment by subhamgcon** [comment]
@cnu1812 should I wait till it is assigned?

**Comment by cnu1812** [comment]
You can start working on it.

**Comment by subhamgcon** [comment]
@cnu1812 Should I add a different template for bug issues and features?

**Comment by cnu1812** [comment]
You can use either yaml or markdown. If you have any doubts do checkout issue template on rap-god-api repo

**Comment by subhamgcon** [comment]
@cnu1812 Added a PR. A review would be really helpful if you are free! Thank you!
