### ISSUE TITLE
[Feature]: Missing PR template

### ISSUE THREAD

**Issue by cnu1812** [dokc/dokc.github.io#37]
Good first issue

**Comment by vish-han** [comment]
@cnu1812 can I work on this issue 😄??

**Comment by cnu1812** [comment]
Go ahead.

**Comment by vish-han** [comment]
thanks @cnu1812 for assigning me , can u suggest me some thing which I should add definitely in the PR template

**Comment by cnu1812** [comment]
The template should include a checklist, A description of the pr what the problem it is solving.

**Comment by AbhijithGanesh** [comment]
CC : @ShivamTyagi12345 and @shreemaan-abhishek

**Comment by vish-han** [comment]
I have a exam in the afternoon,  I will make the PR for this issue in the night🚀😀
