### ISSUE TITLE
Fix typos and grammatical errors in the Operations Page

### ISSUE THREAD

**Issue by subhamgcon** [dokc/dokc.github.io#40]
There are various typographical errors in the [website](https://dokc.github.io). Most of these errors occur in the Operations page, the following files need to be corrected : 
 - [ ] Index 
 - [ ] Principle
 - [ ] Workflows.

**Comment by AbhijithGanesh** [comment]
@subhamgcon Please don't leave an issue empty :)

**Comment by subhamgcon** [comment]
> @subhamgcon Please don't leave an issue empty :)

Sorry, I will close it now.
