### ISSUE TITLE
Unecessary link

### ISSUE THREAD

**Issue by gullapalli9482** [dokc/dokc.github.io#54]
### Describe the bug

An unnecessary "#" symbol is present with some hyperlinked text which is not required since the link to the video is already present.

### To Reproduce

Follow this particular link =>  https://dokc.github.io/docs/Videos/Docker#video
move to the end of the video word, one would find a "#" symbol over there.

### Expected Behavior

Should not be showing it according to me, in any case, if it is required it needs to be hyperlinked with the necessary.

### Screenshot/ Video

![Screenshot from 2022-03-21 19-02-59](https://user-images.githubusercontent.com/75060398/159276475-3f9e11c1-415a-4e3e-b896-7052d6482808.png)

![Screenshot from 2022-03-21 19-03-05](https://user-images.githubusercontent.com/75060398/159276532-43d28194-6aeb-4382-a20c-77f6cbde09bf.png)

**Comment by cnu1812** [comment]
Nice find out, label it as a good first issue.

**Comment by izzarzn** [comment]
### This issue exists in several more pages. 
#### How do I get the source file to fix this I checked in the repo but couldn't find it.

![Screenshot 2022-03-22 at 12 12 39 PM](https://user-images.githubusercontent.com/65058286/159422937-64fa5903-195d-4ac5-bdc2-4c1dccb79386.png)

**Comment by cnu1812** [comment]
> ### This issue exists in several more pages.
> #### How do I get the source file to fix this I checked in the repo but couldn't find it.
> ![Screenshot 2022-03-22 at 12 12 39 PM](https://user-images.githubusercontent.com/65058286/159422937-64fa5903-195d-4ac5-bdc2-4c1dccb79386.png)

dokc.github.io/docs/Working-Groups/

**Comment by AbhijithGanesh** [comment]
@cnu1812 @gullapalli9482 and @izzarzn These aren't unnecessary links, they are references to ID

**Comment by izzarzn** [comment]
> @cnu1812 @gullapalli9482 and @izzarzn These aren't unnecessary links, they are references to ID

But these shouldn't be visible it's visible in multiple pages.
